### ISSUE TITLE
Creating error window in Non UI thread.

### ISSUE THREAD

**Issue by kaviteshsingh** [MathewSachin/DuplicateFileDetector#1]
Hi,

You are creating error window in the non-UI thread and it crashes the app when you try to delete the file which is in use.

// code snippet at crash
                // Intentionally not using a MessageBox so that user could see what was not deleted side by side.
                new Window
                {
                    Title = $"{errors.Count} error(s) occured:",
                    Content = sb.ToString(),
                    ResizeMode = ResizeMode.NoResize,
                    WindowStyle = WindowStyle.ToolWindow,
                    Padding = new Thickness(10)
                }.ShowDialog();

You can test this simply by copying any exe and creating a copy of it and launching it and then perform scan. After the duplicates are found, try deleting the exe and it will hit the issue.

Also, since the code is following MVVM pattern you should not directly create an UI component in the View-Model. If it is really needed, you can create an interface and call the UI element.

**Comment by MathewSachin** [comment]
Thank you for pointing out.
Would fix that soon
